name: Call PR Workflow

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  call-reusable-workflow:
    uses: Enterprise-CMCS/macpro-mdct-core/.github/workflows/pr-notification.yml@main
    with:
      retrieve_endpoint: false
    secrets:
      slack_webhook:  ${{ secrets.INTEGRATIONS_SLACK_WEBHOOK }}