name: gitleaks
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run gitleaks docker
        uses: docker://zricethezav/gitleaks@sha256:e1b35e12a8c6fa8901f060459cfb6b2fc4c484d3afbe3b029733a3bbfab07055 # v8.24.3
        with:
          args: detect --source /github/workspace/ --no-git --verbose
