name: Pull Request Notification

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  notify_integrations_channel:
    runs-on: ubuntu-latest
    # avoiding notifications for automated Snyk Pull Requests and draft pull requests 
    if: github.actor != 'mdct-github-service-account' && !github.event.pull_request.draft
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ":github: A new pull request has been created in ${{ github.repository }} by ${{ github.event.pull_request.user.login }}"
          SLACK_MESSAGE: "${{ github.repository }} does not deploy any infra so no endpoint is available"
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.INTEGRATIONS_SLACK_WEBHOOK }}