name: Workspace Setup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * SUN"
  push:
      branches:
        - "*"
        - "!skipci*"

jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 120 # MacOS runners are more expensive than linux, so we want to be sure to stop any stuck builds.
    environment:
      name: test-ws-setup
    env:
      STAGE_NAME: test-ws-setup
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run workspace setup
        run: |
          sh mdct-setup.sh

      # - name: OP Signin
      #   env:
      #     MDCT_OP_EMAIL: ${{ secrets.MDCT_OP_EMAIL }}
      #     MDCT_OP_KEY: ${{ secrets.MDCT_OP_KEY }}
      #     MDCT_OP_PASSWORD: ${{ secrets.MDCT_OP_PASSWORD }}
      #   run: |
      #     echo $MDCT_OP_PASSWORD | op signin coforma.1password.com $MDCT_OP_EMAIL $MDCT_OP_KEY

      - name: run update env
        run: |
          ls -a
          cd macpro-mdct-mcr
          ./run update-env



  #Notify the tools channel on failure
  notify_on_failure:
    runs-on: ubuntu-latest
    if: failure()
    needs: 
      - test
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ":boom: The weekly workspace setup job failed in ${{ github.repository }}."
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
